### ISSUE TITLE
Add a new description test on Guide.md

### ISSUE THREAD

**Issue by brunobandev** [cloudson/treinando-unit-tests-php#1]
6. Caso o valor fornecido seja fora das regras listadas acima o teste deve garantir o retorno de uma Exception.

:)

**Comment by filhodanuvem** [comment]
Valeu pela sugestão @brunobandev , você não quer aproveitar e abrir uma pull request com a mudança?

**Comment by filhodanuvem** [comment]
Pull request criado #2
