### ISSUE TITLE
Melhorar readme branch "respostas"

### ISSUE THREAD

**Issue by filhodanuvem** [cloudson/treinando-unit-tests-php#5]
Mudar a imagem para aparecer um print de todos os testes passando. 
Abaixo da imagem colocar o texto "Curtiu o desafio? Quer deixar algum feedback para melhorar o repo ou trocar ideia? Abra uma [issue](https://github.com/filhodanuvem/treinando-unit-tests-php/issues/new) e conversamos por la 😄 "

**Comment by lucas-santana** [comment]
Essa issue já foi corrigida?

**Comment by lucas-santana** [comment]
@filhodanuvem essa issue já foi corrigida?

**Comment by filhodanuvem** [comment]
Sim, já está feito @lucas-santana . Fechando em 3, 2 ...
