### ISSUE TITLE
falha do xdebug ao executar os comandos para exibir cobertura

### ISSUE THREAD

**Issue by hemilioaraujo** [cloudson/treinando-unit-tests-php#7]
Ao validar a cobertura de de testes com o comando  `docker run app vendor/bin/phpunit --whitelist ./src/Service --coverage-text --colors ./tests` após fazer a build da imagem é recebido o erro:
> Error:         XDEBUG_MODE=coverage or xdebug.mode=coverage has to be set

**Comment by filhodanuvem** [comment]
Boa @hemilioaraujo, tentei passar a variavel de ambiente pro comando e funcionou. Pode testar ai? 

```
docker run --env XDEBUG_MODE=coverage app vendor/bin/phpunit --whitelist ./src/Service --coverage-text --colors ./tests
```

**Comment by hemilioaraujo** [comment]
Opa, 
funcionou sim, muito obrigado!
Foi falta de conhecimento da minha parte sobre as variáveis de ambiente da imagem.
Eu abri um PR adicionando esta configuração no Dockerfile, mas se preferir posso adicionar ao comando do Guide.md.

**Comment by filhodanuvem** [comment]
Perfeito, sua solução é ótima por não precisar aumentar o comando. 
Obrigado por abrir a issue, não fazia ideia que esse era o comportamento.
